version: "3"
services:
  dashboard:
    image: ${FRONTEND_TAG}
    build: frontend
    depends_on:
      - db
    ports:
      # DASH in numbers
      - "3274:6060"
    volumes:
      - ./plots:/public/plots
    networks:
       - emission
  notebook-server:
    image: ${VIZ_TAG}
    build: 
      context: viz_scripts
      dockerfile: Dockerfile
      args:
        SERVER_IMAGE_TAG: ${SERVER_IMAGE_TAG}
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - WEB_SERVER_HOST=0.0.0.0
      - CRON_MODE=TRUE
      - STUDY_CONFIG=stage-program
    ports:
      # ipynb in numbers
      - "47962:8888"
    networks:
      - emission
    volumes:
      - ./plots:/plots
  db:
    image: mongo:4.4.0
    volumes:
      - mongo-data:/data/db
    networks:
       - emission

networks:
  emission:

volumes:
  mongo-data:

